trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: databricks  # Ensure this group contains your DATABRICKS_TOKEN

- name: DBFS_METADATA_PATH
  value: 'dbfs:/my_code/metadata/sources'  # Target folder in DBFS

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install databricks-cli
    export DATABRICKS_HOST=$DATABRICKS_HOST
    export DATABRICKS_TOKEN=$DATABRICKS_TOKEN
    databricks fs mkdirs $DBFS_METADATA_PATH
    databricks fs cp -r sources $DBFS_METADATA_PATH/ --overwrite --recursive
  displayName: 'Upload Metadata to DBFS'
